# Generated by Django 5.1.2 on 2024-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="wallet_id",
            field=models.CharField(
                default="1234567789123", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
