# Generated by Django 5.1.2 on 2024-11-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_wallet_wallet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                default="2154542154545", max_length=100, unique=True
            ),
            preserve_default=False,
        ),
    ]
