services:
  - type: web
    name: hotelcrew
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn HotelCrew.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: "/opt/render/project/src/firebase.json"
    postDeployCommand: python manage.py migrate --noinput

