#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
# HotelCrew Backend — Server Setup Script
# Run as root or with sudo on a fresh Ubuntu/Debian server.
# Sets up PostgreSQL, Python venv, .env, and a systemd service.
# ─────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colors ───────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

banner() { echo -e "\n${CYAN}══════════════════════════════════════════${NC}"; echo -e "${CYAN}  $1${NC}"; echo -e "${CYAN}══════════════════════════════════════════${NC}\n"; }
info()   { echo -e "${GREEN}[INFO]${NC}  $1"; }
warn()   { echo -e "${YELLOW}[WARN]${NC}  $1"; }
err()    { echo -e "${RED}[ERROR]${NC} $1"; }

# ── Must be root ─────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  err "Please run this script as root or with sudo."
  exit 1
fi

# ── Resolve project directory (where this script lives) ──────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"
info "Project directory: $PROJECT_DIR"

# ─────────────────────────────────────────────────────────────
banner "1/6  Collecting Configuration"
# ─────────────────────────────────────────────────────────────

read -rp "PostgreSQL database name [hotelcrew]: " DB_NAME
DB_NAME="${DB_NAME:-hotelcrew}"

read -rp "PostgreSQL user [hotelcrew]: " DB_USER
DB_USER="${DB_USER:-hotelcrew}"

while true; do
  read -rsp "PostgreSQL password: " DB_PASS
  echo
  if [ -z "$DB_PASS" ]; then
    warn "Password cannot be empty. Try again."
  else
    break
  fi
done

read -rp "Django SECRET_KEY (leave blank to auto-generate): " DJANGO_SECRET
if [ -z "$DJANGO_SECRET" ]; then
  DJANGO_SECRET=$(python3 -c "import secrets; print(secrets.token_urlsafe(50))")
  info "Generated SECRET_KEY."
fi

read -rp "Server domain / IP (for ALLOWED_HOSTS & CSRF) [*]: " SERVER_DOMAIN
SERVER_DOMAIN="${SERVER_DOMAIN:-*}"

read -rp "Email host user (Gmail address, blank to skip): " EMAIL_USER
read -rp "Email host password (app password, blank to skip): " EMAIL_PASS

read -rp "AWS_ACCESS_KEY_ID (blank to skip): " AWS_KEY
read -rp "AWS_SECRET_ACCESS_KEY (blank to skip): " AWS_SECRET

read -rp "Firebase service account JSON path [/app/firebase_credentials/firebase_credentials.json]: " FIREBASE_PATH
FIREBASE_PATH="${FIREBASE_PATH:-/app/firebase_credentials/firebase_credentials.json}"

read -rp "Run Django in DEBUG mode? (y/N): " DEBUG_CHOICE
if [[ "$DEBUG_CHOICE" =~ ^[Yy]$ ]]; then DEBUG_VAL="True"; else DEBUG_VAL="False"; fi

read -rp "Gunicorn workers [3]: " WORKERS
WORKERS="${WORKERS:-3}"

read -rp "Port to run on [8000]: " PORT
PORT="${PORT:-8000}"

# ── System user that will own the service ────────────────────
SVC_USER="hotelcrew"

# ─────────────────────────────────────────────────────────────
banner "2/6  Installing System Packages"
# ─────────────────────────────────────────────────────────────

apt-get update -qq
apt-get install -y -qq \
  python3 python3-pip python3-venv \
  postgresql postgresql-contrib libpq-dev \
  build-essential curl git > /dev/null 2>&1
info "System packages installed."

# ─────────────────────────────────────────────────────────────
banner "3/6  Setting Up PostgreSQL"
# ─────────────────────────────────────────────────────────────

systemctl enable --now postgresql

# Create user & database (idempotent)
su - postgres -c "psql -tc \"SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER'\" | grep -q 1" || \
  su - postgres -c "psql -c \"CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';\""

su - postgres -c "psql -tc \"SELECT 1 FROM pg_database WHERE datname = '$DB_NAME'\" | grep -q 1" || \
  su - postgres -c "psql -c \"CREATE DATABASE $DB_NAME OWNER $DB_USER;\""

su - postgres -c "psql -c \"ALTER USER $DB_USER CREATEDB;\"" # needed for tests
info "PostgreSQL ready  →  db=$DB_NAME  user=$DB_USER"

# ─────────────────────────────────────────────────────────────
banner "4/6  Setting Up Python Virtual Environment"
# ─────────────────────────────────────────────────────────────

# Create system user if it doesn't exist
id -u "$SVC_USER" &>/dev/null || useradd --system --shell /bin/bash --home-dir "$PROJECT_DIR" "$SVC_USER"

python3 -m venv "$PROJECT_DIR/venv"
source "$PROJECT_DIR/venv/bin/activate"
pip install --upgrade pip -q
pip install -r "$PROJECT_DIR/requirements.txt" -q
info "Python venv created at $PROJECT_DIR/venv"

# ─────────────────────────────────────────────────────────────
banner "5/6  Writing .env File"
# ─────────────────────────────────────────────────────────────

ENV_FILE="$PROJECT_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh — $(date '+%Y-%m-%d %H:%M:%S')

SECRET_KEY=$DJANGO_SECRET
DEBUG=$DEBUG_VAL

DATABASE_URL=postgres://$DB_USER:$DB_PASS@localhost:5432/$DB_NAME

AWS_ACCESS_KEY_ID=$AWS_KEY
AWS_SECRET_ACCESS_KEY=$AWS_SECRET

EMAIL_HOST_USER=$EMAIL_USER
EMAIL_HOST_PASSWORD=$EMAIL_PASS

FIREBASE_SERVICE_ACCOUNT_PATH=$FIREBASE_PATH

CSRF_TRUSTED_ORIGINS=https://$SERVER_DOMAIN
EOF

chmod 600 "$ENV_FILE"
info ".env written to $ENV_FILE (mode 600)"

# ── Run migrations & collectstatic ───────────────────────────
cd "$PROJECT_DIR"
python manage.py migrate --noinput
python manage.py collectstatic --noinput 2>/dev/null || true
info "Migrations applied & static files collected."

# ── Fix ownership ────────────────────────────────────────────
chown -R "$SVC_USER":"$SVC_USER" "$PROJECT_DIR"

# ─────────────────────────────────────────────────────────────
banner "6/6  Creating systemd Service"
# ─────────────────────────────────────────────────────────────

SERVICE_FILE="/etc/systemd/system/hotelcrew.service"
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=HotelCrew Django Backend
After=network.target postgresql.service
Requires=postgresql.service

[Service]
Type=notify
User=$SVC_USER
Group=$SVC_USER
WorkingDirectory=$PROJECT_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$PROJECT_DIR/venv/bin/gunicorn HotelCrew.wsgi:application \\
    --bind 0.0.0.0:$PORT \\
    --workers $WORKERS \\
    --timeout 120 \\
    --access-logfile - \\
    --error-logfile -
ExecReload=/bin/kill -s HUP \$MAINPID
Restart=on-failure
RestartSec=5
KillMode=mixed
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable hotelcrew.service
systemctl start hotelcrew.service

info "systemd service created and started."

# ─────────────────────────────────────────────────────────────
banner "✅  Setup Complete!"
# ─────────────────────────────────────────────────────────────

echo -e "${GREEN}Service status:${NC}"
systemctl status hotelcrew.service --no-pager -l || true

echo ""
echo -e "${CYAN}Useful commands:${NC}"
echo -e "  sudo systemctl status  hotelcrew   # check status"
echo -e "  sudo systemctl restart hotelcrew   # restart"
echo -e "  sudo systemctl stop    hotelcrew   # stop"
echo -e "  sudo journalctl -u hotelcrew -f    # live logs"
echo ""
echo -e "${GREEN}Backend is running at → http://$SERVER_DOMAIN:$PORT${NC}"
