# Generated by Django 5.1.2 on 2024-11-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('hoteldetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='hoteldetails.hoteldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionist',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receptionists', to='hoteldetails.hoteldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='hotel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hoteldetails.hoteldetails'),
            preserve_default=False,
        ),
    ]
