# Generated by Django 5.1.2 on 2024-11-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='housekeeping', max_length=40),
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='forgot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
