# Generated by Django 5.1.2 on 2024-11-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_manager_hotel_receptionist_hotel_staff_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=40),
        ),
    ]
