# Generated by Django 5.1.2 on 2024-11-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='otp_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
