# Generated by Django 5.1.2 on 2024-11-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='guest user', max_length=150),
            preserve_default=False,
        ),
    ]
