# Generated by Django 5.1.2 on 2024-11-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emailotp_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
    ]
