# Generated by Django 5.1.2 on 2024-11-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='password',
            field=models.CharField(default='guest user', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user_name',
            field=models.CharField(default='guest user', max_length=150),
            preserve_default=False,
        ),
    ]
