# Generated by Django 5.1.2 on 2024-11-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_staff_department'),
        ('authentication', '0004_alter_user_salary_alter_user_user_profile'),
    ]

    operations = [
    ]
