# Generated by Django 5.1.2 on 2024-11-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emailotp_password_emailotp_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='otp_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
