# Generated by Django 5.1.2 on 2024-11-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20241120_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, default='14-cd-campogalliano-web-1565969801.jpg', null=True, upload_to=''),
        ),
    ]
