# Generated by Django 5.1.2 on 2024-11-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_merge_20241119_2311"),
        ("authentication", "0007_devicetoken"),
    ]

    operations = []
