# Generated by Django 5.1.2 on 2024-11-25 11:14

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_merge_0005_merge_20241119_2311_0007_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_profile",
            field=models.ImageField(
                blank=True,
                default="14-cd-campogalliano-web-1565969801.jpg",
                null=True,
                storage=authentication.models.ProfileImageStorage(),
                upload_to="",
            ),
        ),
    ]
