# Generated by Django 5.1.2 on 2024-11-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20241120_1442'),
        ('authentication', '0009_alter_user_user_profile'),
    ]

    operations = [
    ]
