# Generated by Django 5.1.2 on 2024-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_merge_20241126_1256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.CharField(default="Housekeeping", max_length=40),
        ),
    ]
