# Generated by Django 5.1.2 on 2024-11-04 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('legal_business_name', models.CharField(max_length=255)),
                ('year_established', models.IntegerField()),
                ('license_registration_numbers', models.CharField(max_length=255)),
                ('complete_address', models.TextField()),
                ('main_phone_number', models.CharField(max_length=10)),
                ('emergency_phone_number', models.CharField(max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('total_number_of_rooms', models.PositiveIntegerField()),
                ('number_of_floors', models.PositiveIntegerField()),
                ('valet_parking_available', models.BooleanField(default=False)),
                ('valet_parking_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('payment_methods', models.TextField(help_text='List accepted payment methods')),
                ('room_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_departments', models.PositiveIntegerField()),
                ('department_names', models.TextField(help_text='Comma-separated list of department names')),
                ('staff_excel_sheet', models.FileField(blank=True, null=True, upload_to='staff_sheets/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hoteldetails.hoteldetails')),
            ],
        ),
    ]
