# Generated by Django 5.1.2 on 2024-10-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='legal_business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
