# Generated by Django 5.1.2 on 2024-11-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetails',
            name='staff_excel_sheet',
        ),
    ]
