# Generated by Django 5.1.2 on 2024-11-01 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0002_hoteldetails_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetails',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
