# Generated by Django 5.1.2 on 2024-11-02 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0003_alter_hoteldetails_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldetails',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='hoteldetails',
            name='insurance_documents',
        ),
        migrations.AddField(
            model_name='hoteldetails',
            name='staff_excel_sheet',
            field=models.FileField(blank=True, null=True, upload_to='staff_sheets/'),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='emergency_phone_number',
            field=models.CharField(default='0000000000', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='hotel_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='legal_business_name',
            field=models.CharField(default='hotel', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='room_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
