# Generated by Django 5.1.2 on 2024-11-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0004_remove_customer_room_released_customer_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
