# Generated by Django 5.1.2 on 2024-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteldetails', '0005_customer_checked_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='Regular', max_length=10),
        ),
    ]
