# Generated by Django 5.1.2 on 2024-11-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskAssignment", "0002_announcement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="urgency",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Urgent", "Urgent")],
                default="Normal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In_progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
