# Generated by Django 5.1.2 on 2024-11-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
