# Generated by Django 5.1.2 on 2024-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_leave_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
